name: pull-request-on-master
run-name: Terraform plan on pull request on master branch
on:
  pull_request:
    branches:
      - master

env:
  SEC: ${{ secrets.TEST_SECRET }}

jobs:
  tf_plan:
    permissions:
      contents: read
      id-token: write

    runs-on: ubuntu-latest

    steps:
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@v3

      - name: Print variable
        run: echo ${{ vars.TEST_VARIABLE }}

      - name: Print secret
        run: echo ${{ env.SEC }}

      - name: Is secret there
        if: ${{ env.SEC == 'Secret text' }}
        run: echo "Yes we see the secret"

      - name: Check secret again
        if: ${{ env.SEC == 'Secret tuxt' }}
        run: echo "Secret is tuxt"
